name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configuring environment
        uses: actions/setup-go@v4
        with:
          go-version: ^1.23.4

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Run all webpush tests
        run: go test ./... --race -cover
